import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from "../components/NavBar";
import { Analytics } from '@vercel/analytics/react';
import ScrollToTopButton from "@/components/BacktoTop";
import React from "react";
const inter = Inter({ subsets: ['latin'] })
export const revalidate = 10
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth  ">
      <body className={inter.className}>
      <NavBar />
      {children}
      <ScrollToTopButton/>
      <Analytics />
      </body>
    </html>
  )
}
